FROM node:16.15.1

# Desativar o download do Chromium 
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true

# Diretório de trabalho dentro do container
WORKDIR /backend

# Copiando o conteudo do diretório atual para o diretório "/backend" no contêiner
COPY . .

# Instale as dependências do sistema e do Puppeteer
RUN apt-get update && \
    apt-get install -yq \
    gconf-service \
    libasound2 \
    libatk1.0-0 \
    libc6 \
    libcairo2 \
    libcups2 \
    libdbus-1-3 \
    libexpat1 \
    libfontconfig1 \
    libgcc1 \
    libgconf-2-4 \
    libgdk-pixbuf2.0-0 \
    libglib2.0-0 \
    libgtk-3-0 \
    libnspr4 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libstdc++6 \
    libx11-6 \
    libx11-xcb1 \
    libxcb1 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxi6 \
    libxrandr2 \
    libxrender1 \
    libxss1 \
    libxtst6 \
    ca-certificates \
    fonts-liberation \
    libappindicator1 \
    libnss3 \
    lsb-release \
    xdg-utils \
    wget \
    gnupg && \
    wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && \
    echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends google-chrome-stable && \
    rm -rf /var/lib/apt/lists/* && \
    npm install puppeteer

# Instalar o Chrome através do Puppeteer
RUN npx puppeteer browsers install chrome

# Diretório de cache
RUN mkdir -p /root/.cache/puppeteer

# Expor a porta
EXPOSE 3000

# Comando para executar o aplicativo
CMD ["npm", "start"]
